In [1]:
import tensorflow as tf

In [2]:
# sess = tf.Session()
sess = tf.InteractiveSession()

In [3]:
x = tf.placeholder(tf.float32)
y = 2*x
data = tf.random_uniform([4,5],10)

print(data.eval())
x_data = sess.run(data)

print(data.eval())

[[5.5998383 6.0725183 2.2334857 4.7581534 6.1665087]
 [1.3764267 3.8207278 8.846685  1.4868317 3.8661795]
 [8.688089  3.3333416 4.132329  7.1136255 7.396326 ]
 [4.6965036 5.5193515 7.5645266 3.8471775 1.3269596]]
[[5.5681977 8.789644  8.11651   1.5910263 7.2961273]
 [1.957097  8.633908  1.1919003 3.9333916 8.559553 ]
 [4.5144215 7.99888   1.3843393 2.4103665 1.5774784]
 [8.962536  4.867361  2.5928845 2.409326  5.6403084]]


In [4]:
print(sess.run(y, feed_dict = {x:x_data}))

[[16.755764  16.903692  14.01847   10.231386  19.226152 ]
 [14.684353   6.3915653 10.620326   6.2906437  5.539747 ]
 [19.375877   4.080553  13.380083  13.728259   3.2613354]
 [10.506798  19.049147  18.383718  14.786719  17.17086  ]]


In [6]:
# tf.summary.Filewriter:
writher = tf.summary.FileWriter('summary_dir', sess.graph)

In [16]:
m = 1000
n = 15
p = 2

X = tf.placeholder(tf.float32, name='X')
Y = tf.placeholder(tf.float32, name='Y')

bias = tf.Variable(0.0)
weights = tf.Variable(0.0)

# 计算
Y_hat = X*weights + bias
# Y_hat = tf.matmul(X, weights) + bias

# 损失
loss = tf.square(Y - Y_hat, name='loss')

In [18]:
tf.summary.scalar('loss', loss)

tf.summary.histogram('output', Y_hat)


<tf.Tensor 'output:0' shape=() dtype=string>

In [19]:
init_op = tf.global_variables_initializer()

# tf.merge_all_summaries

with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('graphs', sess.graph)
writer.close()